document ::= module_header (NEWLINE | declaration)* ;
module_header ::= "@모듈 " surface_name canonical_id NEWLINE ;
declaration ::= enum_declaration | data_model_declaration | binary_relation_declaration | unary_relation_declaration | nonempty_declaration | required_relation_declaration | unique_relation_declaration | exclusive_relation_declaration | exhaustive_relation_declaration | coexistent_relation_declaration | ordered_constraint | equality_constraint | field_relation_constraint | role_declaration | action_declaration | policy_declaration | screen_model_operation | screen_field_operation | sum_derivation | recalculation | internal_field_intent | hidden_field_intent ;
enum_declaration ::= surface_name canonical_id topic_marker " 다음 값 중 하나다." NEWLINE enum_value+ ;
enum_value ::= INDENT surface_name canonical_id NEWLINE ;
data_model_declaration ::= surface_name canonical_id topic_marker " 다음 필드들로 구성되어 있다." NEWLINE field_declaration+ ;
field_declaration ::= INDENT surface_name canonical_id ": " requiredness " " type_reference NEWLINE ;
requiredness ::= "필수" | "선택" ;
type_reference ::= "문자열" | "정수" | "불리언" | surface_name ;
binary_relation_declaration ::= surface_reference topic_marker " " surface_reference object_marker " " surface_name canonical_id direction_marker " 가질 수 있다." NEWLINE ;
unary_relation_declaration ::= surface_reference topic_marker " " surface_name canonical_id "에 해당할 수 있다." NEWLINE ;
nonempty_declaration ::= surface_reference topic_marker " 하나 이상 존재해야 한다." NEWLINE ;
required_relation_declaration ::= "모든 " surface_reference topic_marker " " surface_reference object_marker " 하나 이상 가져야 한다." NEWLINE ;
unique_relation_declaration ::= "각 " surface_reference topic_marker " " surface_reference object_marker " 최대 하나만 가질 수 있다." NEWLINE ;
exclusive_relation_declaration ::= relation_list " 중 둘 이상은 동시에 성립할 수 없다." NEWLINE ;
exhaustive_relation_declaration ::= relation_list " 중 하나 이상은 항상 성립해야 한다." NEWLINE ;
coexistent_relation_declaration ::= relation_list topic_marker " 동시에 성립할 수 있다." NEWLINE ;
relation_list ::= surface_reference (", " surface_reference)+ ;
ordered_constraint ::= surface_reference "의 " surface_reference topic_marker " " INTEGER "보다 " ordered_operator " 한다." NEWLINE | surface_reference "의 " surface_reference topic_marker " " INTEGER " " bounded_operator " 한다." NEWLINE ;
ordered_operator ::= "커야" | "작아야" ;
bounded_operator ::= "이상이어야" | "이하여야" ;
equality_constraint ::= surface_reference "의 " surface_reference topic_marker " " literal "이어야 한다." NEWLINE ;
field_relation_constraint ::= surface_reference "의 " surface_reference conjunction_marker " " surface_reference topic_marker " " field_relation " 한다." NEWLINE ;
field_relation ::= "같아야" | "달라야" ;
literal ::= STRING_LITERAL | INTEGER | "참" | "거짓" | surface_name ;
role_declaration ::= surface_name canonical_id topic_marker " 역할이다." NEWLINE ;
action_declaration ::= surface_name canonical_id topic_marker " 행동이다." NEWLINE ;
policy_declaration ::= surface_reference topic_marker " " surface_reference "의 " surface_reference object_marker " " surface_reference "할 수 " policy_effect "." NEWLINE ;
policy_effect ::= "있다" | "없다" ;
screen_model_operation ::= surface_name canonical_id "에서는 " surface_reference object_marker " " model_operation " 수 있다." NEWLINE ;
model_operation ::= "생성할" | "조회할" | "수정할" | "삭제할" ;
screen_field_operation ::= surface_name canonical_id "에서는 " surface_reference "의 " field_list object_marker " " field_operation " 수 있다." NEWLINE ;
field_list ::= surface_reference (", " surface_reference)* ;
field_operation ::= "입력할" | "조회할" | "수정할" ;
sum_derivation ::= surface_reference "의 " surface_reference topic_marker " " surface_reference "의 " surface_reference "의 합계로 계산한다." NEWLINE ;
recalculation ::= surface_reference "의 " surface_reference subject_marker " 바뀔 때 " surface_reference "의 " surface_reference object_marker " 다시 계산한다." NEWLINE ;
internal_field_intent ::= surface_reference "의 " surface_reference topic_marker " 내부 관리에만 사용한다." NEWLINE ;
hidden_field_intent ::= surface_reference "의 " surface_reference topic_marker " 사용자 화면에서 조회하지 않는다." NEWLINE ;
topic_marker ::= "은" | "는" ;
object_marker ::= "을" | "를" ;
subject_marker ::= "이" | "가" ;
conjunction_marker ::= "와" | "과" ;
direction_marker ::= "로" | "으로" ;
surface_reference ::= quoted_name ;
surface_name ::= quoted_name | bare_name ;
quoted_name ::= QUOTED_NAME ;
bare_name ::= NAME_CHAR+ (" " NAME_CHAR+)* ;
canonical_id ::= "(" ID_CHAR+ ")" ;
STRING_LITERAL ::= /"(\\["\\\/bfnrt]|\\u[0-9a-fA-F]{4}|[^"\\\x00-\x1f])*"/ ;
INTEGER ::= /-?(0|[1-9][0-9]*)/ ;
NAME_CHAR ::= /[^\x00-\x20`()\[\]:.,#@"]/ ;
QUOTED_NAME ::= /`[^\x00-\x1f`]+`/ ;
ID_CHAR ::= /[a-z0-9_.]/ ;
INDENT ::= "    " ;
NEWLINE ::= "\n" ;
