'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { Button } from '@dahaze/ui'
import type { PlanningMetadata, PlanningMetadataRevisionResponse } from '@dahaze/api-client'
import { parsePlanningEnvironments, type PlanningEnvironment } from './environments'

export type Environment = PlanningEnvironment
export type SampleValue = string | number | boolean | null
export type SampleRow = { id: string; values: Record<string, SampleValue> }
export type SampleVariants = Record<'normal' | 'empty' | 'long' | 'many', SampleRow[]>
export type SampleModels = Record<string, SampleVariants>
export type MetadataCatalog = { models: { id: string; name: string; fields: { id: string; name: string; typeKind: string; enumVariants?: string[] }[] }[]; screens: { key: string; name: string }[] }

export function MetadataEditor({ metadata, metadataRevision, history, catalog, busy, onSave, onUndo }: { metadata: PlanningMetadata; metadataRevision: number; history: PlanningMetadataRevisionResponse[]; catalog: MetadataCatalog; busy: boolean; onSave: (metadata: { environments: Environment[]; sample_data: Record<string, unknown> }, summary: string) => Promise<number | null>; onUndo: (targetRevision: number) => void }) {
  const [environments, setEnvironments] = useState<Environment[]>(() => parsePlanningEnvironments(metadata.environments))
  const [models, setModels] = useState<SampleModels>(() => parseSampleModels(metadata.sample_data))
  const [baseMetadataRevision, setBaseMetadataRevision] = useState(metadataRevision)
  const [dirty, setDirty] = useState(false)
  const modelIds = Object.keys(models)
  const [selectedModel, setSelectedModel] = useState(modelIds[0] ?? '')
  const [variant, setVariant] = useState<keyof SampleVariants>('normal')
  const [newModelId, setNewModelId] = useState(catalog.models[0]?.id ?? '')
  const [newFieldId, setNewFieldId] = useState('')
  const [saving, setSaving] = useState(false)
  const editGeneration = useRef(0)
  const rows = useMemo(() => models[selectedModel]?.[variant] ?? [], [models, selectedModel, variant])
  const fieldIds = useMemo(() => [...new Set(rows.flatMap((row) => Object.keys(row.values)))], [rows])
  const selectedCatalogModel = catalog.models.find((model) => model.id === selectedModel)
  const markDirty = () => { editGeneration.current += 1; setDirty(true) }
  const updateRows = (next: SampleRow[]) => { setModels((current) => ({ ...current, [selectedModel]: { ...emptyVariants(), ...current[selectedModel], [variant]: next } })); markDirty() }
  const externalConflict = dirty && metadataRevision !== baseMetadataRevision
  const reload = () => { setEnvironments(parsePlanningEnvironments(metadata.environments)); setModels(parseSampleModels(metadata.sample_data)); setBaseMetadataRevision(metadataRevision); setDirty(false) }
  useEffect(() => {
    if (metadataRevision === baseMetadataRevision) return
    if (dirty) return
    queueMicrotask(() => {
      setEnvironments(parsePlanningEnvironments(metadata.environments))
      setModels(parseSampleModels(metadata.sample_data))
      setBaseMetadataRevision(metadataRevision)
    })
  }, [baseMetadataRevision, dirty, metadata, metadataRevision])
  const save = async () => { const generation = editGeneration.current; setSaving(true); try { const nextRevision = await onSave(buildMetadataPatch(metadata, environments, models), '환경과 샘플 데이터 편집'); if (nextRevision !== null) { setBaseMetadataRevision(nextRevision); if (editGeneration.current === generation) setDirty(false) } } finally { setSaving(false) } }
  return <section className="border-t p-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold">환경과 샘플 데이터</h3><p className="mt-1 text-xs text-text-muted">대표 프로젝트는 2–4개 환경으로 검증합니다. 더 많은 환경도 저장할 수 있습니다.</p></div><Button size="sm" onClick={save} disabled={busy || saving || externalConflict}>저장</Button></div>
    {externalConflict ? <div className="mt-3 rounded-control border border-diagnostic-warning/40 bg-diagnostic-warning/5 px-3 py-2 text-xs"><p>다른 화면에서 환경 또는 샘플 데이터가 변경되었습니다. 현재 편집 내용은 그대로 두었습니다.</p><Button className="mt-2" size="sm" variant="outline" onClick={reload}>서버 변경으로 다시 불러오기</Button></div> : null}
    <div className="mt-4 space-y-3">{environments.map((environment, index) => <div key={environment.id} className="grid grid-cols-[1fr_6rem_6rem_auto] gap-2"><input aria-label={`환경 ${index + 1} 이름`} value={environment.name} onChange={(event) => { setEnvironments(updateAt(environments, index, { ...environment, name: event.target.value })); markDirty() }} className="rounded border bg-surface px-2 text-xs" /><label className="text-[10px] text-text-subtle">너비 (CSS px)<input aria-label="환경 너비" type="number" min={240} max={7680} value={environment.width} onChange={(event) => { setEnvironments(updateAt(environments, index, { ...environment, width: bounded(event.target.valueAsNumber, 240, 7680) })); markDirty() }} className="w-full rounded border bg-surface px-2 text-xs" /></label><label className="text-[10px] text-text-subtle">높이 (CSS px)<input aria-label="환경 높이" type="number" min={320} max={4320} value={environment.height} onChange={(event) => { setEnvironments(updateAt(environments, index, { ...environment, height: bounded(event.target.valueAsNumber, 320, 4320) })); markDirty() }} className="w-full rounded border bg-surface px-2 text-xs" /></label><Button size="sm" variant="ghost" onClick={() => { setEnvironments(environments.filter((_, itemIndex) => itemIndex !== index)); markDirty() }}>삭제</Button><label className="col-span-4 text-xs">화면 범위 <select aria-label={`${environment.name} 화면 범위`} value={environment.screenMode} onChange={(event) => { setEnvironments(updateAt(environments, index, { ...environment, screenMode: event.target.value as Environment['screenMode'] })); markDirty() }} className="ml-2 rounded border bg-surface px-2 py-1"><option value="all">모든 화면</option><option value="selected">선택한 화면</option></select></label>{environment.screenMode === 'selected' ? <fieldset className="col-span-4 flex flex-wrap gap-2"><legend className="text-xs text-text-subtle">포함 화면</legend>{catalog.screens.map((screen) => <label key={screen.key} className="text-xs"><input type="checkbox" checked={environment.screenKeys.includes(screen.key)} onChange={(event) => { setEnvironments(updateAt(environments, index, { ...environment, screenKeys: event.target.checked ? [...environment.screenKeys, screen.key] : environment.screenKeys.filter((key) => key !== screen.key) })); markDirty() }} /> {screen.name}</label>)}</fieldset> : <p className="col-span-4 text-xs text-text-subtle">현재와 이후에 추가되는 모든 화면을 포함합니다.</p>}</div>)}</div>
    <Button className="mt-2" size="sm" variant="outline" onClick={() => { setEnvironments([...environments, { id: crypto.randomUUID(), name: `환경 ${environments.length + 1}`, width: 390, height: 844, screenMode: 'all', screenKeys: [] }]); markDirty() }}>환경 추가</Button>
      <div className="mt-5 border-t pt-4"><p className="text-xs font-semibold">모델 샘플 편집</p><div className="mt-2 flex flex-wrap gap-2"><select aria-label="샘플 모델" value={selectedModel} onChange={(event) => setSelectedModel(event.target.value)} className="rounded border bg-surface px-2 text-xs"><option value="">모델 선택</option>{modelIds.map((id) => <option key={id} value={id}>{catalog.models.find((model) => model.id === id)?.name ?? id}</option>)}</select><select aria-label="샘플 상황" value={variant} onChange={(event) => setVariant(event.target.value as keyof SampleVariants)} className="rounded border bg-surface px-2 text-xs"><option value="normal">정상</option><option value="empty">빈 상태</option><option value="long">긴 문구</option><option value="many">많은 데이터</option></select><select aria-label="추가할 모델" value={newModelId} onChange={(event) => setNewModelId(event.target.value)} className="rounded border bg-surface px-2 text-xs"><option value="">추가할 모델</option>{catalog.models.filter((model) => models[model.id] === undefined).map((model) => <option key={model.id} value={model.id}>{model.name}</option>)}</select><Button size="sm" variant="outline" disabled={!newModelId || models[newModelId] !== undefined} onClick={() => { const id = newModelId; setModels((current) => ({ ...current, [id]: emptyVariants() })); setSelectedModel(id); setNewModelId(''); markDirty() }}>모델 추가</Button></div>
      {selectedModel ? <><div className="mt-2 flex gap-2"><select aria-label="새 행의 필드" value={newFieldId} onChange={(event) => setNewFieldId(event.target.value)} className="min-w-0 flex-1 rounded border bg-surface px-2 text-xs"><option value="">필드 선택</option>{selectedCatalogModel?.fields.map((field) => <option key={field.id} value={field.id}>{field.name} · {field.typeKind}</option>)}</select><Button size="sm" variant="outline" disabled={!newFieldId} onClick={() => { const field = selectedCatalogModel?.fields.find((item) => item.id === newFieldId); updateRows([...rows, { id: crypto.randomUUID(), values: { [newFieldId]: initialValue(field?.typeKind) } }]); setNewFieldId('') }}>행 추가</Button></div>{rows.map((row, rowIndex) => <div key={row.id} className="mt-2 border-l-2 pl-2"><div className="flex items-center justify-between"><span className="text-[11px] text-text-subtle">행 {rowIndex + 1}</span><Button size="sm" variant="ghost" onClick={() => updateRows(rows.filter((_, index) => index !== rowIndex))}>삭제</Button></div>{fieldIds.map((fieldId) => { const field = selectedCatalogModel?.fields.find((item) => item.id === fieldId); return <label key={fieldId} className="mt-1 flex items-center gap-2 text-xs"><span className="w-28 truncate">{field?.name ?? fieldId}</span><TypedValue value={row.values[fieldId] ?? null} typeKind={field?.typeKind} enumVariants={field?.enumVariants} onChange={(value) => updateRows(updateAt(rows, rowIndex, { ...row, values: { ...row.values, [fieldId]: value } }))} /></label> })}</div>)}</> : <p className="mt-2 text-xs text-text-subtle">저장된 모델을 선택하거나 새 모델을 추가하세요.</p>}</div>
    {history.length > 0 ? <div className="mt-5 border-t pt-4"><p className="text-xs font-semibold">메타데이터 전체 저장 이력</p>{history.map((entry) => <div key={entry.revision} className="mt-2 flex items-center justify-between text-xs"><span>리비전 {entry.revision} · {entry.summary ?? '메타데이터 변경'}</span><Button size="sm" variant="ghost" disabled={busy || entry.revision === metadataRevision} onClick={() => onUndo(entry.revision)}>전체 메타데이터를 이 상태로</Button></div>)}</div> : null}
  </section>
}

function TypedValue({ value, typeKind, enumVariants, onChange }: { value: SampleValue; typeKind?: string; enumVariants?: string[]; onChange: (value: SampleValue) => void }) { if (typeKind === 'boolean' || typeof value === 'boolean') return <input type="checkbox" checked={value === true} onChange={(event) => onChange(event.target.checked)} />; if (typeKind === 'enum' && enumVariants && enumVariants.length > 0) return <select value={typeof value === 'string' ? value : ''} onChange={(event) => onChange(event.target.value === '' ? null : event.target.value)} className="min-w-0 flex-1 rounded border bg-surface px-2 py-1"><option value="">값 없음</option>{enumVariants.map((variant) => <option key={variant} value={variant}>{variant}</option>)}</select>; if (typeKind === 'integer' || typeKind === 'number' || typeKind === 'decimal' || typeof value === 'number') return <input type="number" step={typeKind === 'integer' ? 1 : 'any'} value={typeof value === 'number' ? value : ''} onChange={(event) => { if (event.target.value === '') { event.currentTarget.setCustomValidity(''); onChange(null); return } const parsed = event.target.valueAsNumber; if (!Number.isFinite(parsed)) return; if (typeKind === 'integer' && !Number.isInteger(parsed)) { event.currentTarget.setCustomValidity('정수만 입력할 수 있습니다.'); event.currentTarget.reportValidity(); return } event.currentTarget.setCustomValidity(''); onChange(parsed) }} className="min-w-0 flex-1 rounded border bg-surface px-2 py-1" />; return <input value={value ?? ''} onChange={(event) => onChange(event.target.value)} className="min-w-0 flex-1 rounded border bg-surface px-2 py-1" /> }
function initialValue(typeKind?: string): SampleValue { return typeKind === 'boolean' ? false : typeKind === 'integer' || typeKind === 'number' ? 0 : '' }
export function buildMetadataPatch(original: PlanningMetadata, environments: Environment[], models: SampleModels): { environments: Environment[]; sample_data: Record<string, unknown> } { const sample = typeof original.sample_data === 'object' && original.sample_data !== null ? original.sample_data : {}; return { environments, sample_data: { ...sample, models } } }
export function parseSampleModels(value: PlanningMetadata['sample_data']): SampleModels { if (typeof value !== 'object' || value === null || typeof value.models !== 'object' || value.models === null) return {}; const result: SampleModels = {}; for (const [modelId, variants] of Object.entries(value.models)) { if (typeof variants !== 'object' || variants === null) continue; const parsed = emptyVariants(); for (const name of Object.keys(parsed) as (keyof SampleVariants)[]) parsed[name] = parseRows(variants[name]); result[modelId] = parsed } return result }
function parseRows(value: unknown): SampleRow[] { return Array.isArray(value) ? value.flatMap((raw, index) => typeof raw === 'object' && raw !== null && typeof raw.values === 'object' && raw.values !== null ? [{ id: typeof raw.id === 'string' ? raw.id : `row-${index}`, values: Object.fromEntries(Object.entries(raw.values).filter((entry): entry is [string, SampleValue] => entry[1] === null || ['string', 'number', 'boolean'].includes(typeof entry[1]))) }] : []) : [] }
function emptyVariants(): SampleVariants { return { normal: [], empty: [], long: [], many: [] } }
function updateAt<T>(items: T[], index: number, value: T): T[] { return items.map((item, itemIndex) => itemIndex === index ? value : item) }
function bounded(value: number, min: number, max: number): number { return Number.isFinite(value) ? Math.min(max, Math.max(min, value)) : min }
