'use client'

import { useMemo, useState } from 'react'
import { Button } from '@dahaze/ui'
import type { PlanningMetadata, PlanningMetadataRevisionResponse } from '@dahaze/api-client'

export type Environment = { id: string; name: string; width: number; height: number; screenKeys: string[] }
export type SampleValue = string | number | boolean | null
export type SampleRow = { id: string; values: Record<string, SampleValue> }
export type SampleVariants = Record<'normal' | 'empty' | 'long' | 'many', SampleRow[]>
export type SampleModels = Record<string, SampleVariants>

export function MetadataEditor({ metadata, revision, history, busy, onSave, onUndo }: { metadata: PlanningMetadata; revision: number; history: PlanningMetadataRevisionResponse[]; busy: boolean; onSave: (metadata: { environments: Environment[]; sample_data: Record<string, unknown> }, summary: string) => Promise<boolean>; onUndo: (targetRevision: number) => void }) {
  const [environments, setEnvironments] = useState<Environment[]>(() => parseEnvironments(metadata.environments))
  const [models, setModels] = useState<SampleModels>(() => parseSampleModels(metadata.sample_data))
  const modelIds = Object.keys(models)
  const [selectedModel, setSelectedModel] = useState(modelIds[0] ?? '')
  const [variant, setVariant] = useState<keyof SampleVariants>('normal')
  const [newModelId, setNewModelId] = useState('')
  const [newFieldId, setNewFieldId] = useState('')
  const [saving, setSaving] = useState(false)
  const rows = useMemo(() => models[selectedModel]?.[variant] ?? [], [models, selectedModel, variant])
  const fieldIds = useMemo(() => [...new Set(rows.flatMap((row) => Object.keys(row.values)))], [rows])
  const updateRows = (next: SampleRow[]) => setModels((current) => ({ ...current, [selectedModel]: { ...emptyVariants(), ...current[selectedModel], [variant]: next } }))
  const save = async () => { setSaving(true); try { await onSave(buildMetadataPatch(metadata, environments, models), '환경과 샘플 데이터 편집') } finally { setSaving(false) } }
  return <section className="border-t p-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold">환경과 샘플 데이터</h3><p className="mt-1 text-xs text-text-muted">대표 프로젝트는 2–4개 환경으로 검증합니다. 더 많은 환경도 저장할 수 있습니다.</p></div><Button size="sm" onClick={save} disabled={busy || saving}>저장</Button></div>
    <div className="mt-4 space-y-3">{environments.map((environment, index) => <div key={environment.id} className="grid grid-cols-[1fr_5rem_5rem_auto] gap-2"><input aria-label={`환경 ${index + 1} 이름`} value={environment.name} onChange={(event) => setEnvironments(updateAt(environments, index, { ...environment, name: event.target.value }))} className="rounded border bg-surface px-2 text-xs" /><input aria-label="환경 너비" type="number" value={environment.width} onChange={(event) => setEnvironments(updateAt(environments, index, { ...environment, width: bounded(event.target.valueAsNumber, 240, 1920) }))} className="rounded border bg-surface px-2 text-xs" /><input aria-label="환경 높이" type="number" value={environment.height} onChange={(event) => setEnvironments(updateAt(environments, index, { ...environment, height: bounded(event.target.valueAsNumber, 320, 2000) }))} className="rounded border bg-surface px-2 text-xs" /><Button size="sm" variant="ghost" onClick={() => setEnvironments(environments.filter((_, itemIndex) => itemIndex !== index))}>삭제</Button>{environment.screenKeys.length > 0 ? <p className="col-span-4 text-xs text-text-subtle">포함 화면 {environment.screenKeys.length}개 · 화면 흐름에서 편집</p> : null}</div>)}</div>
    <Button className="mt-2" size="sm" variant="outline" onClick={() => setEnvironments([...environments, { id: crypto.randomUUID(), name: `환경 ${environments.length + 1}`, width: 390, height: 844, screenKeys: [] }])}>환경 추가</Button>
    <div className="mt-5 border-t pt-4"><p className="text-xs font-semibold">모델 샘플 편집</p><div className="mt-2 flex flex-wrap gap-2"><select aria-label="샘플 모델" value={selectedModel} onChange={(event) => setSelectedModel(event.target.value)} className="rounded border bg-surface px-2 text-xs"><option value="">모델 선택</option>{modelIds.map((id) => <option key={id}>{id}</option>)}</select><select aria-label="샘플 상황" value={variant} onChange={(event) => setVariant(event.target.value as keyof SampleVariants)} className="rounded border bg-surface px-2 text-xs"><option value="normal">정상</option><option value="empty">빈 상태</option><option value="long">긴 문구</option><option value="many">많은 데이터</option></select><input aria-label="새 모델 ID" value={newModelId} onChange={(event) => setNewModelId(event.target.value)} placeholder="새 모델 stable ID" className="rounded border bg-surface px-2 text-xs" /><Button size="sm" variant="outline" disabled={!newModelId.trim() || models[newModelId.trim()] !== undefined} onClick={() => { const id = newModelId.trim(); setModels((current) => ({ ...current, [id]: emptyVariants() })); setSelectedModel(id); setNewModelId('') }}>모델 추가</Button></div>
      {selectedModel ? <><div className="mt-2 flex gap-2"><input aria-label="새 필드 ID" value={newFieldId} onChange={(event) => setNewFieldId(event.target.value)} placeholder="필드 stable ID" className="min-w-0 flex-1 rounded border bg-surface px-2 text-xs" /><Button size="sm" variant="outline" disabled={!newFieldId.trim()} onClick={() => { const field = newFieldId.trim(); updateRows([...rows, { id: crypto.randomUUID(), values: { [field]: '' } }]); setNewFieldId('') }}>행 추가</Button></div>{rows.map((row, rowIndex) => <div key={row.id} className="mt-2 border-l-2 pl-2"><div className="flex items-center justify-between"><span className="text-[11px] text-text-subtle">행 {rowIndex + 1}</span><Button size="sm" variant="ghost" onClick={() => updateRows(rows.filter((_, index) => index !== rowIndex))}>삭제</Button></div>{fieldIds.map((field) => <label key={field} className="mt-1 flex items-center gap-2 text-xs"><span className="w-28 truncate font-mono">{field}</span><TypedValue value={row.values[field] ?? null} onChange={(value) => updateRows(updateAt(rows, rowIndex, { ...row, values: { ...row.values, [field]: value } }))} /></label>)}</div>)}</> : <p className="mt-2 text-xs text-text-subtle">저장된 모델을 선택하거나 새 모델을 추가하세요.</p>}</div>
    {history.length > 0 ? <div className="mt-5 border-t pt-4"><p className="text-xs font-semibold">메타데이터 전체 저장 이력</p>{history.slice(0, 5).map((entry) => <div key={entry.revision} className="mt-2 flex items-center justify-between text-xs"><span>리비전 {entry.revision} · {entry.summary ?? '메타데이터 변경'}</span><Button size="sm" variant="ghost" disabled={busy || entry.revision === revision} onClick={() => onUndo(entry.revision)}>전체 메타데이터를 이 상태로</Button></div>)}</div> : null}
  </section>
}

function TypedValue({ value, onChange }: { value: SampleValue; onChange: (value: SampleValue) => void }) { if (typeof value === 'boolean') return <input type="checkbox" checked={value} onChange={(event) => onChange(event.target.checked)} />; if (typeof value === 'number') return <input type="number" value={value} onChange={(event) => onChange(event.target.valueAsNumber)} className="min-w-0 flex-1 rounded border bg-surface px-2 py-1" />; return <input value={value ?? ''} onChange={(event) => onChange(event.target.value)} className="min-w-0 flex-1 rounded border bg-surface px-2 py-1" /> }
export function buildMetadataPatch(original: PlanningMetadata, environments: Environment[], models: SampleModels): { environments: Environment[]; sample_data: Record<string, unknown> } { const sample = typeof original.sample_data === 'object' && original.sample_data !== null ? original.sample_data : {}; return { environments, sample_data: { ...sample, models } } }
export function parseSampleModels(value: PlanningMetadata['sample_data']): SampleModels { if (typeof value !== 'object' || value === null || typeof value.models !== 'object' || value.models === null) return {}; const result: SampleModels = {}; for (const [modelId, variants] of Object.entries(value.models)) { if (typeof variants !== 'object' || variants === null) continue; const parsed = emptyVariants(); for (const name of Object.keys(parsed) as (keyof SampleVariants)[]) parsed[name] = parseRows(variants[name]); result[modelId] = parsed } return result }
function parseRows(value: unknown): SampleRow[] { return Array.isArray(value) ? value.flatMap((raw, index) => typeof raw === 'object' && raw !== null && typeof raw.values === 'object' && raw.values !== null ? [{ id: typeof raw.id === 'string' ? raw.id : `row-${index}`, values: Object.fromEntries(Object.entries(raw.values).filter((entry): entry is [string, SampleValue] => entry[1] === null || ['string', 'number', 'boolean'].includes(typeof entry[1]))) }] : []) : [] }
function emptyVariants(): SampleVariants { return { normal: [], empty: [], long: [], many: [] } }
function parseEnvironments(value: PlanningMetadata['environments']): Environment[] { if (!Array.isArray(value)) return []; return value.flatMap((raw, index) => typeof raw === 'object' && raw !== null ? [{ id: typeof raw.id === 'string' ? raw.id : `environment-${index}`, name: typeof raw.name === 'string' ? raw.name : `환경 ${index + 1}`, width: typeof raw.width === 'number' ? raw.width : 390, height: typeof raw.height === 'number' ? raw.height : 844, screenKeys: Array.isArray(raw.screenKeys) ? raw.screenKeys.filter((item): item is string => typeof item === 'string') : [] }] : []) }
function updateAt<T>(items: T[], index: number, value: T): T[] { return items.map((item, itemIndex) => itemIndex === index ? value : item) }
function bounded(value: number, min: number, max: number): number { return Number.isFinite(value) ? Math.min(max, Math.max(min, value)) : min }
