"""working tree commits and locks

공유 작업 트리, commit, 파일 잠금 (ADR-0008). 이 마이그레이션은 새 테이블만 추가한다.
기존 documents·document_revisions·스냅샷 테이블은 옛 화면 코드를 삭제하는 단계에서 삭제한다.

Revision ID: 7c47bda3e1b8
Revises: e713c2b1ad46
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c47bda3e1b8'
down_revision: Union[str, Sequence[str], None] = 'e713c2b1ad46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commits',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('project_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'seq', name='uq_commit_project_seq')
    )
    op.create_index(op.f('ix_commits_project_id'), 'commits', ['project_id'], unique=False)
    op.create_table('tree_files',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('project_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('committed_path', sa.String(length=500), nullable=True),
    sa.Column('committed_text', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_files_project_id'), 'tree_files', ['project_id'], unique=False)
    op.create_index('uq_tree_file_path_alive', 'tree_files', ['project_id', 'path'], unique=True, postgresql_where='NOT deleted')
    op.create_table('tree_folders',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('project_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'path', name='uq_tree_folder_path')
    )
    op.create_index(op.f('ix_tree_folders_project_id'), 'tree_folders', ['project_id'], unique=False)
    op.create_table('commit_changes',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('commit_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('old_path', sa.String(length=500), nullable=True),
    sa.Column('new_path', sa.String(length=500), nullable=True),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commit_changes_commit_id'), 'commit_changes', ['commit_id'], unique=False)
    op.create_index(op.f('ix_commit_changes_file_id'), 'commit_changes', ['file_id'], unique=False)
    op.create_table('file_locks',
    sa.Column('file_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('project_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('holder', sa.String(length=200), nullable=False),
    sa.Column('actor_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('last_write_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['tree_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_file_locks_holder'), 'file_locks', ['holder'], unique=False)
    op.create_index(op.f('ix_file_locks_project_id'), 'file_locks', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_locks_project_id'), table_name='file_locks')
    op.drop_index(op.f('ix_file_locks_holder'), table_name='file_locks')
    op.drop_table('file_locks')
    op.drop_index(op.f('ix_commit_changes_file_id'), table_name='commit_changes')
    op.drop_index(op.f('ix_commit_changes_commit_id'), table_name='commit_changes')
    op.drop_table('commit_changes')
    op.drop_index(op.f('ix_tree_folders_project_id'), table_name='tree_folders')
    op.drop_table('tree_folders')
    op.drop_index('uq_tree_file_path_alive', table_name='tree_files', postgresql_where='NOT deleted')
    op.drop_index(op.f('ix_tree_files_project_id'), table_name='tree_files')
    op.drop_table('tree_files')
    op.drop_index(op.f('ix_commits_project_id'), table_name='commits')
    op.drop_table('commits')
    # ### end Alembic commands ###
